apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: url-shortener-ingress
  namespace: url-shortener
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: url-shortener.homelab.local
      http:
        paths:
          # Frontend — Hauptseite
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
          # Backend API
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
          # Redirect-Endpunkt
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
